name: survey_builder
publish_to: 'none'
description: "Survey Builder App"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  built_collection: ^5.1.1
  design_system_flutter:
    path: ../../packages/design_system_flutter
  survey_backend_api:
    path: ../../packages/contracts/generated/dart

  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
